name = "franklin-submit-wrapper"
main = "src/index.js"
compatibility_date = "2023-05-08"
account_id="4e9f130dfe711d433018ca7f7f06fb37"

node_compat = true

kv_namespaces = [
    { binding = "FRANKLIN_UPLOAD_KV", id = "be66afa01333423b846161c50726635e", preview_id = "09669ede79b7445eb87c278b9dd627b5"}
]

[vars]
ORIGIN_HOSTNAME = "main--mammotome--hlxsites.hlx.page"
WHITELISTED_HOST = "['localhost:3000', 'hlxsites.hlx.page', 'hlxsites.hlx.live', 'franklin-submit-wrapper.crispr-api.workers.dev']"
GOOGLE_RECAPTCHA_URL = 'https://www.google.com/recaptcha/api/siteverify'
HOST_URL="https://franklin-submit-wrapper.mammotome.workers.dev"
SITE_ID="fac8f079-f817-4127-be6b-700b19217904"
SITE_FILE_UPLOAD_PATH="sites/mammotome/attachments"
SITE_FILE_UPLOAD_ID="016MFFNR462FXZSZJATNE3QM2AZVXZQS7X"
APP_SCOPE="offline_access user.read Files.ReadWrite.All Sites.ReadWrite.All"
MARKETO_ACCESS_TOKEN_KEY="accessToken"
MARKETO_URL="https://797-MKX-025.mktorest.com"
CLIENT_ID=""
CLIENT_SECRET=""
MARKETO_FIELD_MAP='{"First Name":"firstName","Last Name":"lastName","Facility Name":"facilityName","Product Interest":"productInterest","Solution Interest":"solutionInterest","service":"service","message":"message"}'
MARKETO_ENABLED_FORMS='["contact"]'
